- Source/Applications/SystemCenter/package.json
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/ByAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/FawgLineSegmentWizard/SectionSelect.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/LineSegmentWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AddToGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/ByAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Company/ByCompany.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/ByCustomer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceHealthReport/DeviceContacts.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceHealthReport/DeviceHealthReport.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceHealthReport/DownloadedFiles.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/ByLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationDrawings.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ByMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/Page3.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/GenericSlice.ts
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/AdditionalUserFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupItem.tsx
Updates references to react-table based on the changes in https://github.com/GridProtectionAlliance/gpa-gemstone/pull/25.
~Submitted as a draft PR because the react-table changes have yet to be merged or pushed to npm.~
> Fix tables based on changes in react-table

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupAssetGroup.tsx
> Fixed bug where event propagated to parent div

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/ByAssetGroup.tsx
> Fixed issue in adding new asset group.

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
https://support.gridprotectionalliance.org/tickets/1093
> Fix for customer delete controller

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
https://support.gridprotectionalliance.org/tickets/1082
> Changed format of datafile date to 24 hr

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/Asset.tsx
https://support.gridprotectionalliance.org/tickets/1321
> Changed type display on drop-down to descriptions over names

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
https://support.gridprotectionalliance.org/tickets/1064
> Fix for asset key unique checking on meter add asset button

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ChannelScaling/ChannelScalingWrapper.tsx
Was still a little broken, fix confirmed to work now
> More fixes for scaling window

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteAssetForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterTab.tsx
Fixed various UI Labels.
Will also require a `gpa-gemstone` update
> Ticket_1440_1441

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/LocationPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
https://support.gridprotectionalliance.org/tickets/1295
> Made default Location at null in NMW

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
Fixed issue where a break in typing would unselect the additional fields box
> Ticket_1445

- Source/Applications/SystemCenter/Controllers/ExternalDB/LineSegmentWizardController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationManagment/ApplicationNode.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/FawgLineSegmentWizard/LineSegmentWizard.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
Note that this won't run until #85 is merged and this is rebased since #85 fixes a dependency issue
> Line segment wizard fix

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/MeterAssetGroup.tsx
Fix double scrollbar in asset group details by removing the overflow property from the table bodies.
> Ticket_1433

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx
Fix search bar on user groups page.
> Ticket_1491

- Build/Scripts/SystemCenter.buildproj
- Build/Scripts/UpdateDependencies.bat
`UpdateDependencies.bat`
- Get the repo version from Git tags with git describe --tags --abbrev=0
- Set remotebranch to either master or ud-%version% depending on the PushToVersionBranch option
- After pushing, invoke the AfterPushScript to create the pull request
`SystemCenter.buildproj`
- Override the AfterPushToServer target, invoking the AfterPushScript to create the pull request
> Integration of nightly build with Jenkins

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ConfigurationHistory/ConfigurationHistory.tsx
Add button to go to meter details from meter configuration history.
> Ticket_1501

- Source/Applications/SystemCenter/Controllers/OpenXDA/Assets/OpenXDAAssetController.cs
- Source/Applications/SystemCenter/Model/DetailedMeterAsset.cs
- Source/Applications/SystemCenter/SystemCenter.csproj
- Source/Applications/SystemCenter/package.json
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
> Add fault detection logic to meter assets tab Ticket_1145

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
Changes the errors in the New Meter Wizard to tell the user to contact their administrator.
> Ticket_1477

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/FawgLineSegmentWizard/SectionEdit.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/FawgLineSegmentWizard/SectionSelect.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
> Ticket_1508_1509_1526

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/ByUser.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx
Fix User and User Group sorting.
> Ticket_1489 Fix User and User Group Sorting

- Source/Applications/SystemCenter/AppDebug.config
- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
- Source/Applications/SystemCenter/Model/ChannelTemplate.cs
- Source/Applications/SystemCenter/SystemCenter.csproj
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ApplicationCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/Customer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DeviceIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/Location.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/MATLABAnalytic.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Meter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/TemplateWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/BySetting.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataOperations.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SystemCenter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/User.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/UserGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/global.d.ts
This addresses:
Ticket_1484
Ticket_1479
And adds a Progressbar to the Wizard
Also has the tab_caching branch merged into it
> New meter wizard updates

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/MeterAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/Customer.tsx
Quantities in the Asset Group Info tab will update once an Asset/Meter/Asset Group is added without having to navigate away from the page. (Code cleanup for Customer.tsx)
> ticket_1302

- Build/Scripts/SystemCenter.buildproj
- Build/Scripts/UpdateDependencies.bat
This fixes 
(1) the default git path
(2) the additional submodule commands
> Nightlybuild fix

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
Fixes tab refresh issues related to asset channels and their connections.
> ticket_1325

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SystemCenter.tsx
Made alterations to categories with new/updated/moved items.
> Ticket 1552

- Source/Applications/SystemCenter/Model/Security/SecurityGroup.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/GroupForm.tsx
Fixed issue making all new Groups DataBase Goups.
Also fixed Table Layout in By UsersGroup Page
> Fixed Bugs in User Group UI

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
Updates Event Types table with changes made to an event type without reloading the page or navigating away.
> ticket_SC-31

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AdditionalFields/ByAdditionalField.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalDB.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDB.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTable.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableFields.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTables.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalXDAFields/ExternalDBXdaFields.tsx
Additional Fields Layout Fixes
> Additional Fields Layout Fixes

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
Replace Data Start Time with NaN If no event is present instead of 1/1/0001 
I think we can safely assume The Romans didn't have PQ Data
> Fixed 1/1/1 data start time

- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/AssetGroupSelection.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/ByAllSubscription.tsx
Add button to remove email subscriptions
> SC-39 Remove Email Subscriptions

- Source/Applications/SystemCenter/Model/DetailedMeterAsset.cs
- Source/Applications/SystemCenter/package.json
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
Added Designation to Table in Meter Page. Should not be needed in Asset Page.
There is a sepperate issue to add it to the modal - but that will require a more extensive rewrite of that page
> XDA-7 Added Designation to Meter Page

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AdditionalFields/ByAdditionalField.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ByApplicationCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationManagment/ApplicationNode.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/ByAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/ByAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/ByCustomer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DB/DBCleanup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceHealthReport/DeviceHealthReport.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventTag/ByEventTag.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalDB.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalTable.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/ByLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/ByMATLABAnalytic.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/ByMagDurCurve.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ByMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/ByWidget.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/ByWidgetCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataOperations.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/Setting.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/ByUser.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
> Added StorageID to retain search filters between tabs

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
- Source/Applications/SystemCenter/Model/ValueList.cs
- Source/Applications/SystemCenter/SystemCenter.csproj
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupDelete.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupItem.tsx
This adds logic to prevent deletion of `ValueList Groups` that are neccesarry or used.
It also prevents deletion of `ValueList Items` that are in use.
This fixes:
SC-4 SC-23 
@elwills lot's of ui messages
I may need a gemstone update to swap some of the warnings to be single button
> Value List Update

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
- Source/Applications/SystemCenter/package.json
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/ByMagDurCurve.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/CurveForm.tsx
- Updated frontend with magdurcurve interface changes
- Updated controller with model changes
> MagDurCurves

- Source/Applications/SystemCenter/Model/Security/UserAccount.cs
Fix for User Page that got missed previously
> Fixed User Queries to take email for external accounts

- Source/Applications/SystemCenter/Controllers/OpenXDA/Meters/OpenXDAMeterDataController.cs
Companion for https://github.com/GridProtectionAlliance/openXDA/pull/269
I made the changes earlier, but apparently forgot to push and submit the PR.
> Remove references to retired reports

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventTag/ByEventTag.tsx
Created a warning delete confirmation for event tags.
> SC-94 Delete Confirmation for Event Tag

- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/EmailForm.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/ByReport.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/DatasourceUI/DataSourceTesting.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/DatasourceUI/DataSourceWindow.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/GeneralInfo.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/ReportForm.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/ReportPage.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/Subscriptions.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/Template.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/TestEmail.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/TriggerWindow.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/AssetGroupSelection.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/ConfirmCarrier.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/ConfirmEmail.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/ConfirmPhone.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/AddAllSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/ByAllSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/BySubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/EmailSelect.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/NewEventSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/Success.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Report/NewReportSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Report/ReportSelect.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Report/Success.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/UserSelect.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/TrippedNodes/ByTrippedNode.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/UserInformation/ByUserInformation.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/global.d.ts
This is PR 2 for notification pages. Updates the rest of the tables and layout.
Relies on https://github.com/GridProtectionAlliance/openXDA/pull/285
> SC-45 Notification Pages Tables and Layout (2 / 2)

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Meter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
Added button to redirect user to meter details in a new tab
> SC-70 Added Meter Property button in NMW

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/UserForm.tsx
> SC-74 SC-75

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DataQualityIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DownloadedFilesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/MiMDIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenMICIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenXDAIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/Reason.tsx
Implements changes to the tables on the Device Issues Page, so that they are complete, up to date, and sort accurately.
> issue_SC-26

- Source/Applications/SystemCenter/Controllers/OpenXDA/OpenXDALocationController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationAsset.tsx
Turns out column sort issues was a key issue, and the key issue was caused by not having the distinct as part of the select clause
> Fixing Column Sort Issues SC-97

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteAssetTab.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterTab.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/SystemSettingsTab.tsx
Replaced window.innerHeights with flex
> SC-104 Remote openXDA Instances pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ChannelScaling/ChannelScalingForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ChannelScaling/ChannelScalingWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Meter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterConfigurationHistory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterEventChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterMaintenance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterTrendChannel.tsx
used flex for meter files
SC-86
> Sc 99 meters page

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDB.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTables.tsx
Took available space using flex
> SC-105 External Databases Pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/ByWidget.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/global.d.ts
> SC-119 Remove Enabled checkbox from PQ Browser Widget modal

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/LineSegmentWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/SourceImpedanceWindow.tsx
Changed window.innerHeights with flex to use available space
> SC-101 Flex Assets Page

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ApplicationCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ApplicationCategoryInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/Applications.tsx
Removed margins and used flex instead of window.innerHeight
> SC-111 Application Categories Pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/ByLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/Location.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationDrawings.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationImages.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationMeter.tsx
used flex for substation files
> SC-100 Substations Page

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/ByAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/MeterAssetGroup.tsx
Used flex in asset group pages
> SC-102 Asset Group Pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/ByCustomer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/Customer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/CustomerAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/CustomerInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/CustomerMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/MDMKeys.tsx
Replaced window.innerHeight with flex
> SC-103 Customer Pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalTable.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTable.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableFields.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTables.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalXDAFields/ExternalDBXdaFields.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/TableTesting/ResultDisplay.tsx
Replaced window.innerHeights with flex to take up all available space.
> SC-106 External Tables Page 

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupItem.tsx
Replaced window.innerHeight with flex to use all available space
> SC-107 Value Lists Pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupItem.tsx
Used flex instead of window.innerHeight
> SC-108 Channel Groups page

- Source/Applications/SystemCenter/Controllers/ExternalDB/LineSegmentWizardController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/FawgLineSegmentWizard/SectionEdit.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/LineSegmentWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
> Automated Key and Name for Line Segments

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/ByWidgetCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/CategoryInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetByCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetCategory.tsx
removed margins and used flex instead of window.innerHeight
> SC-109 Browser Tabs Page

- Source/Applications/SystemCenterNotification/Scripts/TSX/CellCarrier/ByCellCarrier.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailCategory/ByEmailCategory.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailCategory/EmailCategoryForm.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailCategory/EmailCategoryWindow.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/ByEmailType.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/EmailForm.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/GeneralInfo.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/UserInformation/ByUserInformation.tsx
Adds input maximums to 
My Subscriptions > Cell Phone (200)
System Settings > Email Category - Name (50)
System Settings > Event Notifications - Name (50), File Path (200)
System Settings > Cell Carrier - Name, Transform (200)
> SC-151 input maximums

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsKeyModal.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
Fixed edit button to show the value in the value column
> SC-127 value field nmw step 7

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SystemCenter.tsx
Adding route to `Customers` page back in after accidental deletion.
> Add back Customers page routing

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/AdditionalUserFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/Permissions.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/ByUser.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/Info.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/User.tsx
Removed margins and used flex instead of window.innerHeight
> SC-112 Users page

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/GroupUsers.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/Info.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/UserGroup.tsx
Used flex instead of window.innerHeight
> SC-113 User Groups

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ByMeter.tsx
Removed excess white space at the bottom of the card
> SC-144 ByMeter White Space

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Advanced/MeterDataDelete.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Advanced/MeterDataMerge.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Advanced/MeterDataRescue.tsx
Took all available space for the cards
> SC-125 Meter Advanced Pages

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ConfigurationHistory/ConfigurationHistory.tsx
> SC-124 Processed File Scroll

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/EventTypeForm.tsx
The EventTypes Other and Test do not allow the user to pick valid assets.
Page is Event Types
> SC-145 Added check for 'test' and 'other' when rendering form

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
Modified return path `handle.done()` in `$.ajax` call
> SC-166 Changed path to send user to Line segment page after delete

- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/AssetGroupSelection.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/ConfirmCarrier.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/ConfirmEmail.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/ConfirmPhone.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/AddAllSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/EmailSelect.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/NewEventSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/Success.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Report/NewReportSubscription.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Report/ReportSelect.tsx
Swaps the layout of the "Subscribe to Event" page
> SC-158 Updated branch to swap the Asset Group and Notification category dropdown

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ApplicationCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/NoteWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/Customer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceHealthReport/DeviceHealthReport.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/Location.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/MATLABAnalytic.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/MATLABAnalyticInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/MATLABAnalyticSQLSetting.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Meter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/User.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/UserGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroup.tsx
Removed the margins present on the cards on all the pages listed in the sidebar.
Depends on for Note component:
https://github.com/GridProtectionAlliance/gpa-gemstone/pull/298
> SC-148 remove margins

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/TableTesting/QueryTestDialog.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/TableTesting/ResultDisplay.tsx
Fixed its frequent erroring, and added a loading screen to table
> SC-165 test table query error while loading

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceForm.tsx
Changed to Initialize data push
> SC-160 Changed button name

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx
> SC-167 Data Reader Error checking

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
Now in format: AssetName (AssetKey)
> SC-181 Added the AssetName to Asset Category Modal

- Source/Applications/SystemCenter/Controllers/OpenXDA/OpenXDALocationController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/ByLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationDrawings.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ByMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterInfo.tsx
Added pagination to regular tables in Substation category
> SC-146 Substation Pagination

- Source/Applications/SystemCenter/Controllers/OpenXDA/Meters/OpenXDAMeterController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ChannelScaling/ChannelScalingForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterEventChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterMaintenance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterTrendChannel.tsx
> SC-150 Meters Sorting

- Source/Applications/SystemCenter/Controllers/OpenXDA/OpenXDALocationController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationMeter.tsx
Fixed sorting for the Substations pages
> SC-168 Substation's Sorting

- Source/Applications/SystemCenterNotification/Controllers/OpenXDAControllers.cs
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/DatasourceUI/DataSourceModal.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/DatasourceUI/DataSourceWindow.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/EmailPage.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/GeneralInfo.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/Template.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/TriggerUI/EventSelect.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/TriggerUI/TriggerWindow.tsx
Added a delete function to OpenXDAController
Updated the page to have a trash/edit icon in the right column
> SC-153 Data Source delete functionality

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationImages.tsx
Added the LayoutGrid to LocationImages.tsx on the Substation page for cleaner layout.
> SC-132 image layout

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/MeterAssetGroup.tsx
Fixed sorting for Asset Groups
> SC-175 Asset Groups Sorting

- Source/Applications/SystemCenter/Controllers/OpenXDA/Assets/OpenXDAAssetController.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/ByAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/LineSegmentWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/SourceImpedanceWindow.tsx
> SC-169 Assets Sorting

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelPage.tsx
`useEffect` was not updating properly.
> SC-141 NMW now properly accepts files

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
- Source/Applications/SystemCenter/Model/ValueList.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupDelete.tsx
SC-201
SC-202
If we need to make this value list required I can do that, but I'm not sure it's necessary.
> Ctl parser

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/ByCustomer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/CustomerAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/CustomerMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/MDMKeys.tsx
> SC-184 Customer's Sorting

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationManagment/ApplicationNode.tsx
> SC-188 SSO Application

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DataQualityIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DeviceIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DownloadedFilesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/MiMDIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenMICIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenXDAIssuesPage.tsx
Clean up Device Issues Pages UI.
> SC-195 Device Issues Pages Cleanup

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableFields.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBTableInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalXDAFields/ExternalDBXdaFields.tsx
Fixed External Tables button UI and sorting
> SC-189 External Tables Sorting

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ApplicationCategoryInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/Applications.tsx
Fixed Application Categories Sorting
> SC-192 Application Categories Sorting

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
- Source/Applications/SystemCenter/Model/ChannelGroup.cs
- Source/Applications/SystemCenter/SystemCenter.csproj
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroupItem.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/global.d.ts
Relies on OpenXDA changes: https://github.com/GridProtectionAlliance/openXDA/pull/336 and Gemstone changes: https://github.com/GridProtectionAlliance/gpa-gemstone/pull/306
> SC-194 Channel Groups Sorting

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteAssetForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteAssetTab.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterTab.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/SystemSettingsTab.tsx
Fixed sorting for Remote Meter and Remote Assets. Relies on Gemstone changes: https://github.com/GridProtectionAlliance/gpa-gemstone/pull/308 and OpenXDA changes: https://github.com/GridProtectionAlliance/openXDA/pull/337
> SC-196 RemoteXDA Instance Sorting

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterTab.tsx
Added a filter to remove currently selected meters on the Remote page --- preventing one from assigning the same meter multiple times.
> SC-136 Filters Currently Selected Meters

- Source/Applications/SystemCenter/Controllers/OpenXDA/Assets/OpenXDAAssetController.cs
- Source/Applications/SystemCenter/Model/Security/UserAccount.cs
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetChannel.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetConnection.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/ByUser.tsx
> Small fixes

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
updated phaseMatch switch statement
> SC-203 Now looks for 'Ir' in channel name to set to Residual

- Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs
Removed the line where we were changing it from Instantaneous
> SC-207 CTL files use Instantaneous Characteristic Type

- Source/Applications/SystemCenter/package-lock.json
- Source/Applications/SystemCenter/package.json
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterTab.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/SystemSettingsTab.tsx
Requires The following PRs:
✅ https://github.com/GridProtectionAlliance/openXDA/pull/356**
✅  https://github.com/GridProtectionAlliance/gpa-gemstone/pull/317
SC-161
SC-185
SC-199
> Remote fixes

- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/EmailPage.tsx
- Source/Applications/SystemCenterNotification/Web.config
The `Event Notifications` > Select Email > `Delete` Modal now has a functional `Cancel` button.
> SC-230 SystemCenter Notifications: Fixed Cancel Button Delete Modal

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx
The Detailed meter view, on the Asset tab, now links to the asset in a new tab
> SC-225 Assets Links

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetForm.tsx
N/A
<br />
---
Updated EventWidgets repository pointer.
Cleaned up options for PQBrowser Widgets by removing empty as an option.
<br />
---
<h4>How/Where to test OR Detail how it was tested</h4>  
Added a new ITOA PQBrowser Widget.
Tried Adding a widget that does not exist.
---
<h4>Related PRs</h4>  
https://github.com/GridProtectionAlliance/SEBrowser/pull/101
> PQ browser widget fixes

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ByApplicationCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ByChannelGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/ByCustomer.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DB/DBCleanup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/EventType/ByEventType.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalDB.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalTable.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/ByMATLABAnalytic.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/ByMagDurCurve.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceForm.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/ByWidget.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataOperations.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
Changed relevant pages to GenericByPage component
Depends on https://github.com/GridProtectionAlliance/openXDA/pull/411
> Updated To GenericByPage

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/AssetPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelSelector.tsx
*<h6>Fixing up tab (and general assignment) issues found after PR 528.</h6>*  
<br /> 
---
<h5>Related PRs</h5>  
*<h6>Fixes up issues from [this](https://github.com/GridProtectionAlliance/SystemCenter/pull/528).</h6>*
> Rework of asset page channel selection

- Source/Applications/SystemCenter/Controllers/OpenXDA/OpenXDAControllers.cs
- Source/Applications/SystemCenter/Controllers/SystemCenter/AppHostController.cs
- Source/Applications/SystemCenter/SystemCenter.csproj
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AppHost/AppHost.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AppHost/ApplicationCard.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AppHost/ConsoleWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AppHost/NodeStats.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/EditionTooltip.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/ConfigurationSlice.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
*<h6>[SC-208](https://gridprotectionalliance.atlassian.net/browse/SC-208), [SC-219](https://gridprotectionalliance.atlassian.net/browse/SC-219), [SC-223](https://gridprotectionalliance.atlassian.net/browse/SC-223)</h6>*
<br />
---
*<h6>Initial commit of Enterprise Edition for SystemCenter.</h6>*  
<br />
[SC-208]: https://gridprotectionalliance.atlassian.net/browse/SC-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SC-219]: https://gridprotectionalliance.atlassian.net/browse/SC-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SC-223]: https://gridprotectionalliance.atlassian.net/browse/SC-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> Ee intial sc

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/ByLocation.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationAsset.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationMeter.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
<h6>SC-168</h6>
<br />
---
<h6>Substation/Location Tables are Organized</h6>  
<br />
---
2. Click Substations in sidebar
3. Verify that Name is first column and is the default, ascending sort key
4. Click on Location (GOTHAM CITY S1003 has both Meters and Assets)
5. Click Meter tab and verify that Name is first column and is the default, ascending sort key
6. Click Asset tab and verify that Name is first column and is the default, ascending sort key
> SC-168 Substations

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetSelect.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/MeterAssetGroup.tsx
<h6>SC-175</h6>
---
<h6>AssetGroup Tables</h6>  
<br />
---
2. Click AssetGroup
3. Verify that Name is first column
4. Click on an Asset
5. Click Asset tab and verify Name is first, Key Second
6. Click Add Transmission Assets and verify tables have Name first, Key second
7. Cancel
8. Click Meter and verify Name is first, Key is Second
9. Click Add Meter and verify Name is first, Key is second
> SC-175 Asset Groups

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ByApplicationCategory.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
<h6>SC-192</h6>
---
<h6>Application Category Tables</h6>  
---
2. Click Application Category
3. Verify table is sorted by `Sort Order` column and ascending
4. Click a row and swap to next tab
5. Verify table is sorted by `Sort Order` column and ascending
> SC-192 Application Categories

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DataQualityIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/MiMDIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenMICIssuesPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/OpenXDAIssuesPage.tsx
<h6>SC-253</h6>
---
<h6>Device Health Tables</h6>  
---
2. Click Device Health
3. Click a row
4. Go to each tab (besides the Download tab) and make sure all tables are sorted by Date - ascending
> SC-253 Device Health Tables

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx
<h6>SC-254</h6>
---
<h6>Data Files Table</h6>  
---
2. Click Data Files
3. Verify table is sorted by date descending and font is smaller for the headers.
> SC-254 Data Files Tables

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetByCategory.tsx
<h6>SC-256</h6>
---
<h6>PQ Browser Widget Tables</h6>  
---
2. Click Browser Widgets
3. Click a row and swap to table tab
4. Verify table has columns named 'Name' and 'Type'
> SC-256 PQ Widget Table

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/Setting.tsx
<h6>SC-257</h6>
---
<h6>Settings Tables</h6>  
---
2. Click Any of the settings pages, they all share the component so one page will do
3. Verify table has a column named 'Setting'
> Sc 257 settings

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/AdditionalUserFieldSlice.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/AdditionalUserFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/GroupUsers.tsx
<h6>SC-259</h6>
---
<h6>User Tables</h6>  
---
2. Click Users
3. Verify Username is sorted ascending
4. Click a user
5. Navigate to additional fields and verify table is sorted Field Ascending
6. Click User Groups
7. Verify Names is sorted Ascending
8. Click a group with a User Table
9. Navigate to User tab and verify Username is sorted Ascending
> SC-259 User Tables

- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/ExternalDBUpdate.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/GenericByPage.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx
<h6>SC-260</h6>
---
<h6>Common Component Tables</h6>  
---
2. Click Customer
3. Verify the fontSize is smaller. This table is using GBP
4. Click Asset
5. Click External Database
6. Verify table is sorted by 'Name' ascending
> SC-260 Common Components Tables

- Source/Applications/SystemCenter/SystemCenter.csproj
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/AssetInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsProperties.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsTable.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsValueField.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/AdditionalFieldsWindow.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/CustomerInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterInfo.tsx
- Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
*<h6>[SC-296](https://gridprotectionalliance.atlassian.net/browse/SC-296)</h6>*
<br />
---
*<h6>Bugfixes for additional fields.</h6>*  
<br />
---
<h4>NMW, additional fields tab, and additional fields properties were tested.</h4>  
[SC-296]: https://gridprotectionalliance.atlassian.net/browse/SC-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Addl fields

- Source/Applications/SystemCenterNotification/Scripts/TSX/CellCarrier/ByCellCarrier.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/DatasourceUI/DataSourceModal.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/EmailForm.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/Template.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/EmailTypes/TriggerUI/TriggerWindow.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/DatasourceUI/DataSourceModal.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/ReportForm.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Report/Template.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/AssetGroupSelection.tsx
- Source/Applications/SystemCenterNotification/Scripts/TSX/UserInformation/ByUserInformation.tsx
*<h6>Format example: SC-###, GEM-###</h6>*
SC-231
<br />
---
*<h6>Include what is being changed and why.</h6>*  
Added help messages to various fields
<br />
---
<h4>How/Where to test OR Detail how it was tested</h4>  
*<h6>Include path/link to any necessary files if applicable.</h6>*  
1.   Tested help messages on all pages
---
<h5>Related PRs</h5>  
*<h6>Include links to any related PRs here.</h6>*
> Added help messages to Subscribe page

- Source/Applications/SystemCenter/Controllers/OpenXDA/Meters/OpenXDAMeterController.cs
*<h6>Endpoints are not respecting trend channel flag.</h6>*  
<br />
---
<h4>How/Where to test OR Detail how it was tested</h4>  
1.   NMW was tested.
2.   Channel scaling page was tested.
> Added trend flag field to controller endpoints

- Source/Applications/SystemCenterNotification/Controllers/EmailTypeController.cs
[XDA-63](https://gridprotectionalliance.atlassian.net/browse/XDA-63)
<br />
---
A call to XDA nodes is being added so that we may reconfigure scheduled email nodes.
<br />
---
<h5>Related PRs</h5>  
[XDA #508](https://github.com/GridProtectionAlliance/openXDA/pull/508)
[XDA-63]: https://gridprotectionalliance.atlassian.net/browse/XDA-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added notification on Scheduled email type change
