Source/Applications/SystemCenter/Controllers/OpenXDA/Assets/OpenXDAAssetController.cs, Source/Applications/SystemCenter/Controllers/OpenXDA/Meters/OpenXDAMeterController.cs, Source/Applications/SystemCenter/Controllers/SystemCenter/SystemCenterController.cs, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetAttribute/Asset.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterAsset.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/Page3.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/AssetSlice.ts
Fixed the following Bugs per TVAs request:
New Meter Wizard is missing fields for Characteristic and Harmonic 
Event Channels – Channel field is blank for all channels but there is a warning stating that “SourceIndices is a required field”.
Trend Channels tab displays Harmonic field but all Harmonics are set to 0. Added logic to populate these in New Meter Wizard
Transmission Assets – Channels tab does not display any channels so I cannot verify what channels are mapped
=> Various Temporary Fixes in the New Meter Wizard

Source/Applications/SystemCenterSetup/SystemCenter.wxs
Add missing dependencies to the installer to make Azure AD authentication work properly.
=> Add missing dependencies to WiX installer script

Source/Applications/SystemCenter/ServiceHost.Designer.cs, Source/Applications/SystemCenter/ServiceHost.resx
Renamed `openXDA.ErrorLog.txt` and `openXDA.StatusLog.txt` to `SystemCenter.ErrorLog.txt` and `SystemCenter.StatusLog.txt` respectively. This has just bothered me for a long time.
=> Fixed ErrorLog.txt and StatusLog.txt file names

Source/Applications/SystemCenter/ServiceHost.cs
Exceptions here don't seem to cause problems for release builds, but it's annoying with a debugger attached. Better if we handle it properly.
=> Do not attempt to log stack frames that do not exist

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/CurveForm.tsx
This resolves the issue where the `Add` button adds a new point. It copies the previous point to make sure everything is still valid, but used to copy the reference instead of creating a new point at the same location.
=> Fixed MagDur Curve edit

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ByApplicationCategory.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationManagment/ApplicationNode.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetAssetGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupAssetGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroupInfo.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/MeterAssetGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/CommonComponents/SearchFields.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalDB.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ExternalDBForm.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/LocationMeter.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterForm.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceForm.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataOperations.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/Setting.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/ByUser.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/UserForm.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
`Asset Groups`
- Removed `Users` from `Info` tab
`Data Files`
- Changed column name to `File Path` to match filter
`Remote openXDA Instances`
- Changed all labels to `URL`
`External Databases`
- Changed all `Name` labels to `Table Name`
- Changed filter label to `External DB` (added space)
`Application Categories`
- Changed filter label to `Sort Order`
- Removed `Value` filter
`Value Lists`
- Changed labels to `Description`
`SystemCenter`, `OpenXDA`, & `MiMD`
- Changed filter label to `Setting Name`
- Changed labels to `Current Value`
`OpenXDA Data Operations` & `OpenXDA Data Readers`
- Changed filter labels to `Assembly Name`, `Type Name`, and `Load Order`
`SSO Applications`
- Changed filter labels to `Application Name` and `Node ID`
`Users`
- Changed labels to `Username`
- Removed …
=> Ticket_1390, Ticket_1322

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ByApplicationCategory.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationManagment/ApplicationNode.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/ByCustomer.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DB/DBCleanup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceHealthReport/DeviceHealthReport.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ExternalDB/ByExternalDB.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/ByMagDurCurve.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Advanced/MeterDataMerge.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/MultipleAssetsPage.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ProcessedFile/ByFile.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/ByWidgetCategory.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataOperations.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/DataReaders.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Settings/Setting.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/ByUser.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/ByUserGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ByValueListGroup.tsx
More UI fixes.
- Add `( )` to search feedback messages for consistency throughout System Center.
- Update object names in search feedback messages in some cases.
- Add missing period to the end of warning messages.
=> Search feedback

Source/Applications/SystemCenter/Web.config, Source/Applications/SystemCenterNotification/NotificationPages.csproj, Source/Applications/SystemCenterNotification/Web.config, Source/Applications/SystemCenterNotification/packages.config
Resolves the following error in Notification Pages.
> Owin pipeline not loaded. Try running 'update-package Microsoft.Owin.Host.SystemWeb -reinstall' from NuGet Package Manager Console.
The main thing I failed to realize was that `Microsoft.Owin.Host.SystemWeb` was not installed at all in **NotificationPages**. The recommended command was successfully updating the package in **SystemCenter**; thereby returning no errors, making no changes to the repo, and yet failing to fix the error. So this ended up being mostly just a major ~~headache~~ dependency cleanup until I got it to the point where I could see the dependency was missing. The real fix was...
`Install-Package Microsoft.Owin.Host.SystemWeb -IgnoreDependencies -ProjectName NotificationPages -Version 3.1.0`
=> Clean up dependencies to fix Owin Startup

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SystemCenter.tsx
ticket_1075
-Fix `DeviceHealthReport` so that the nav link stays blue when `DeviceIssuesPage` is opened.
-Fix typos in `miMD` and `User Groups` links so they turn blue when selected.
=> Fix nav links so they turn blue when selected.

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/ChannelScaling/ChannelScalingForm.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/MeterEventChannel.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelPage.tsx
ticket_1442
Update the Meter > Event Channels tab to use `ConfigurableTable` and adjust column widths for smaller screens.
Set width to `auto` for some fields in Event Channels and NMW Channel Page so the columns fill in space by hidden columns.
Fix issue in Channel Scaling Form that did not update local storage when CT/PT ratio was deleted.
Fix for buttons being disabled when CT/PT ratios are not `1`.
=> Channel updates

Source/Applications/SystemCenter/AppDebug.config, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ApplicationCategory/ApplicationCategory.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Asset/Asset.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AssetGroups/AssetGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ChannelGroup/ChannelGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Customer/Customer.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/DeviceIssuesPage/DeviceIssuesPage.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/Location.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MATLABAnalytics/MATLABAnalytic.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Meter/Meter.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstance.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SEBrowser/WidgetCategory.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/SystemCenter.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/User/User.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/User/UserGroup/UserGroup.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroup.tsx
Ticket_1501
Fix tab caching functionality so that the application remembers the previous selection for `Meters`, `Substations`, `Application Categories`, `Value Lists`, `Users`, and `User Groups`. This addresses the issue with the new `Configuration History` button not returning the user to the expected tab in the above mentioned ticket.
=> Tab caching

Build/Scripts/SystemCenter.buildproj, Build/Scripts/UpdateDependencies.bat
Added the --init flag since it may be the first build after cloning the repository in which case it is necessary to initialize submodules.
I verified that it does not cause any issues if it is already initialized.
=> Added init flag to submodule update

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteXDAInstanceMain.tsx
Fix the admin check, otherwise the default event would be fired causing the page to go to the ByMeters page.
=> SC-51 Add RemoteXDA Connection Fix

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/ValueListGroup/ValueListGroupForm.tsx
The tooltip no longer displays when the help text is blank.
=> SC-90 changed empty string to 'undefined' for tooltip

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AdditionalFields/AdditionalFieldForm.tsx
Ensures FieldName is not null before calling match
=> SC-85 Blank Additional Field Page

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/NewMeterWizard.tsx
Uses the `setState` to set the NMW state, and uses `setError` to set the error states in the child components.
tested with this code:
```typescript
function causeError(): void {
setError(['error']);
}
```
```typescript
/*line 500*/ <button className="btn btn-block btn-danger pull-right" onClick={causeError}>Force Error</button>
```
to cause an error state and then reset it with the reset button.
=> SC-140 Reset Button resets error states

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/AssetPage.tsx
Added a filterChannel function
=> SC-206 Filters out used Channels

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/AssetPage.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelSelector.tsx
The channel pick list in the NMW on the Asset step has been fixed to show the channel names more completely.
=> SC-204 Fixed Selector Layout

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/AssetPage.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/NewMeterWizard/ChannelPage.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Store/Store.ts
<h6>SC-252</h6>
---
<h6>New Meter Wizard Tables</h6>  
---
2. Click Add Meter
3. Continue to step 3 Channel
4. Upload a test file
5. Verify that Identifier is still sorted col and is ascending
7. Continue to step 9
8. Click Assign
9. Verify Customer table is sorted by name ascending
=> SC-252 NMW Tables

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteAssetTab.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/RemoteXDA/RemoteMeterTab.tsx
<h6>SC-196</h6>
---
<h6>Remote Instance Tables</h6>  
---
2. Click Remote openXDA Instance
3. Click a row
4. Switch to Meter Tab
5. Verify that relevant column names are in the format "Local " + "Name"/"Key"/"Alias" or "Remote" + "Name"/"Key"/"Alias"
6. Switch to Asset Tab and do the same (p. 6)
=> SC-196 Remote OpenXDA Instance

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/Location/ByLocation.tsx
*<h6>Part of SC-305</h6>*
<br />
---
*<h6>The pagination on the Substation page did not switch pages. I've added a useEffect to do the proper PageSearch when necessary.</h6>*  
<h4>Testing</h4>  
1. You will need multiple pages in order to test page swapping.  </br>
2. Click through next pages with Paging component
> To get multiple pages with just the vmsqlhost data set I modified the `GSF.Web` file's `GetPagedList` function to 1 EntryPerPage instead of 50, built, and copied it over and this allowed for fewer entries per page, thus more pages. The front-end will still render all on the proper page (the first), but it will have more pages (as if there was just one entry per page). Correct behavior in this case is: Page one has all the …
=> Fixed Pagination Bug 

Source/Applications/SystemCenterNotification/Scripts/TSX/Store.tsx, Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/ByAllSubscription.tsx, Source/Applications/SystemCenterNotification/Scripts/TSX/Subscriptions/Event/BySubscription.tsx
<h4>SC-261</h4>  
---
*<h6>The All Subscription and My Subscription tables were showing all of the emails sent. This is unintended and has been fixed. Now it only shows each email once. As the ticket describes.</h6>*  
---
<h4>Testing</h4>  
1.   Open SystemCenter Notifications
2. Go to My Subscriptions
3. (Given that you have subscriptions) This will display only one of each type
4. Go to All Subscriptions
5. Verify that displayed is only one of each subscription per user
---
<h5>Related PRs</h5>  
*<h6>[OpenXDA has the needed DB View changes](https://github.com/GridProtectionAlliance/openXDA/pull/461)</h6>*
=> SC-261 Subscription Table

Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/AppHost/ConsoleWindow.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/ByMagDurCurve.tsx, Source/Applications/SystemCenter/wwwroot/Scripts/TSX/SystemCenter/MagDurCurves/CurveForm.tsx
<h6>SC-244, SC-248</h6>
<br />
---
<h6>UI issues and modal code clean up as per tickets. </h6>
<br />
=> Small things

Source/Applications/SystemCenter/Configuration/SystemSettings.cs, Source/Applications/SystemCenter/Controllers/ControllerActivator.cs, Source/Applications/SystemCenter/ServiceHost.cs, Source/Applications/SystemCenter/Startup.cs, Source/Applications/SystemCenter/SystemCenter.csproj, Source/Applications/SystemCenter/SystemCenterEngine.cs
[SC-246](https://gridprotectionalliance.atlassian.net/browse/SC-246)
---
<h6>Adding controller activator (similar to XDA's) to system center so that we can set higher timeouts in the settings. Additional steps may be needed for meter deletion.</h6>
<br />
---
<h4>How/Where to test OR Detail how it was tested</h4>  
1.   Using different settings categories on controllers was tested.
2.   Other adapter types were tested.
3.   Model Controller compatibility was tested (with [this branch](https://github.com/GridProtectionAlliance/gsf/tree/SC_ControllerActivation)).
4.   Base functionality with no changes was tested.
[SC-246]: https://gridprotectionalliance.atlassian.net/browse/SC-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> Sc controller activation

Build/Scripts/BuildBeta.bat, Build/Scripts/BuildNightly.bat
Nightly builds have been failing ever since #745 because that PR uses newer C# language features that aren't available in VS2019.
=> Update build scripts to use VS2022
